# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: frontend
  source_entry_path: ''
  public_output_path: frontend

  extensions:
    - .ts
    - .js # required to resolve webpack node_modules dependencies
    - .sass
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default

  domain: localhost
  dev_server:
    host: localhost
    port: 4000
    https: false

test:
  <<: *default

  public_output_path: packs-test

production:
  <<: *default
